/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

import static org.example.Book.readBookFromUser;

public class App {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        var lib = new Library();
        ConsoleCommands commands = new ConsoleCommands();
        System.out.println("Willkommen in meiner virtuellen Bibliothek");
        System.out.println("Tippen Sie 'help' ein, um die Liste der verfügbaren Befehle anzuschauen");
        boolean running = true;
        while (running) {
            String input = sc.nextLine().trim().toLowerCase();
            switch (input) {
                case "help":
                    commands.showCommands();
                    break;
                case "add":
                    Book newBook = readBookFromUser(sc);
                    lib.addBook(newBook);
                    System.out.println("Buch '" + newBook.getTitle() + "' wurde erfolgreich hinzugefügt!");
                    break;
                case "search":
                    System.out.println("do you want to search in authors or title?");
                    String searchType = sc.nextLine().toLowerCase();
                    searchByProperty(sc,lib,searchType);
                    break;
                case "exit":
                    running = false;
                    break;


            }
        }

        sc.close();


    }

    private static void searchByProperty(Scanner sc,Library lib,String propertyType) {
        System.out.println("Search for the " + propertyType );
        String searchTerm = sc.nextLine().toLowerCase();
        if (propertyType.equals("author")) {
            Book book = lib.searchBookByAuthor(searchTerm);
            System.out.println("Founded Book -> " + book.getTitle() );
        } else if (propertyType.equals("title")) {
            Book book = lib.searchBookByTitle(searchTerm);
            System.out.println("Founded Book -> " + book.getTitle() );
        }

    }
}
