/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.util.HashMap;
import java.util.Map;

import static org.junit.Assert.*;

public class AppTest {


    @Test
    public void TestAddBook_ValidBook() {
        Library library = new Library();
        Book book = (new Book("The Starwars","John mc","1283","Active"));
        library.addBook(book);
        assertTrue(library.getBooksList().contains(book));
    }
}
